task 13.8 finished
AdamPawlinski/task-13.8 pull request #1
Opened 2018-04-07 04:40 UTC by AdamPawlinski

Task finished. Please accept merging.

2018-04-09 08:37 UTC, matwjablonski requested changes

2018-04-09 08:37 UTC, matwjablonski commented on index.html
> +    <title>Connected</title>
meta?

2018-04-15 04:25 UTC, AdamPawlinski commented
meta tag added. Ask for acceptance.

2018-04-16 05:35 UTC, matwjablonski approved these changes

2018-09-14 03:55 UTC, merged